/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package superapp;

import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuário do Windows
 */
public class ItemMercado extends javax.swing.JPanel {

    /**
     * Creates new form ItemMercado
     */
    
    public Mercado.item produto;
    public Mercado.Carrinho carrinho;
    
    public ItemMercado(Mercado.item produto, Mercado.Carrinho carrinho) {
        
        initComponents();
        this.produto = produto;
        this.carrinho = carrinho;
        
        labelNome.setText(produto.getNome()+" • R$"+String.format("%.2f", produto.getPreco())+"/"+produto.getUnidade());
        
        try{
            java.io.File arquivoImagem = new java.io.File("src/main/java" + produto.getImg());
    
            if(arquivoImagem.exists()) {
                ImageIcon iconeOriginal = new ImageIcon(arquivoImagem.getAbsolutePath());

                java.awt.Image imgRedimensionada = iconeOriginal.getImage().getScaledInstance(
                    labelImg.getPreferredSize().width, 
                    labelImg.getPreferredSize().height, 
                    java.awt.Image.SCALE_SMOOTH
                );
        
            labelImg.setIcon(new ImageIcon(imgRedimensionada));
            labelImg.setText(""); 
            }
            else {
                labelImg.setText("Não encontrada");
                System.out.println("Arquivo não existe em: " + arquivoImagem.getAbsolutePath());
            }
        }
        catch(Exception e){
            labelImg.setText("Erro!");
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImg = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spinnerQtd = new javax.swing.JSpinner();
        botaoAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        labelImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImg.setText("img");
        labelImg.setPreferredSize(new java.awt.Dimension(135, 115));

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNome.setForeground(new java.awt.Color(0, 0, 0));
        labelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNome.setText("Nome");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Quantidade");

        spinnerQtd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        spinnerQtd.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        botaoAdd.setBackground(new java.awt.Color(0, 102, 51));
        botaoAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoAdd.setForeground(new java.awt.Color(255, 255, 255));
        botaoAdd.setText("Adicionar ao carrinho");
        botaoAdd.addActionListener(this::botaoAddActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(botaoAdd)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelImg, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinnerQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAdd)
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddActionPerformed
        // TODO add your handling code here:
        int qtd = (int) spinnerQtd.getValue();
        
        carrinho.adicionar(produto, qtd);
    }//GEN-LAST:event_botaoAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botaoAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelImg;
    private javax.swing.JLabel labelNome;
    private javax.swing.JSpinner spinnerQtd;
    // End of variables declaration//GEN-END:variables
}
