/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package superapp;

import javax.swing.ImageIcon;

/**
 *
 * @author Usuário do Windows
 */
public class ItemCarrinho extends javax.swing.JPanel {

    /**
     * Creates new form ItemCarrinho
     */
    
    Item produto;
    Carrinho carrinho;
    
    public ItemCarrinho(Item produto, Carrinho carrinho) {
        initComponents();
        
        this.produto = produto;
        this.carrinho = carrinho;
        
        labelNomeCarrinho.setText(produto.getNome());
        labelQtdCarrinho.setText(carrinho.getQuantItens()+" "+produto.getUnidade());
        labelPrecoUn.setText("R$"+String.format("%.2f", produto.getPreco()));
        labelPrecoTotal.setText("R$"+(produto.getPreco()*carrinho.quantItens));
        
        try{
            java.io.File arquivoImagem = new java.io.File("src/main/java" + produto.getImg());
    
            if(arquivoImagem.exists()) {
                ImageIcon iconeOriginal = new ImageIcon(arquivoImagem.getAbsolutePath());

                java.awt.Image imgRedimensionada = iconeOriginal.getImage().getScaledInstance(
                    labelImgCarrinho.getPreferredSize().width, 
                    labelImgCarrinho.getPreferredSize().height, 
                    java.awt.Image.SCALE_SMOOTH
                );
        
            labelImgCarrinho.setIcon(new ImageIcon(imgRedimensionada));
            labelImgCarrinho.setText(""); 
            }
            else {
                labelImgCarrinho.setText("Sem foto");
            }
        }
        catch(Exception e){
            labelImgCarrinho.setText("Erro!");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImgCarrinho = new javax.swing.JLabel();
        labelNomeCarrinho = new javax.swing.JLabel();
        labelQtdCarrinho = new javax.swing.JLabel();
        labelPrecoUn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRemover = new javax.swing.JLabel();
        labelPrecoTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        labelImgCarrinho.setForeground(new java.awt.Color(0, 0, 0));
        labelImgCarrinho.setText("img");
        labelImgCarrinho.setPreferredSize(new java.awt.Dimension(60, 60));
        add(labelImgCarrinho);
        labelImgCarrinho.setBounds(12, 17, 64, 60);

        labelNomeCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNomeCarrinho.setForeground(new java.awt.Color(0, 0, 0));
        labelNomeCarrinho.setText("Nome");
        add(labelNomeCarrinho);
        labelNomeCarrinho.setBounds(90, 10, 69, 32);

        labelQtdCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelQtdCarrinho.setForeground(new java.awt.Color(0, 0, 0));
        labelQtdCarrinho.setText("Quantidade");
        add(labelQtdCarrinho);
        labelQtdCarrinho.setBounds(90, 70, 64, 16);

        labelPrecoUn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPrecoUn.setForeground(new java.awt.Color(0, 0, 0));
        labelPrecoUn.setText("Preço un.");
        add(labelPrecoUn);
        labelPrecoUn.setBounds(180, 70, 52, 16);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemover.setText("Remover");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(btnRemover)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnRemover)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(409, 0, 110, 104);

        labelPrecoTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPrecoTotal.setForeground(new java.awt.Color(0, 0, 0));
        labelPrecoTotal.setText("jLabel5");
        add(labelPrecoTotal);
        labelPrecoTotal.setBounds(290, 40, 60, 25);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnRemover;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelImgCarrinho;
    private javax.swing.JLabel labelNomeCarrinho;
    private javax.swing.JLabel labelPrecoTotal;
    private javax.swing.JLabel labelPrecoUn;
    private javax.swing.JLabel labelQtdCarrinho;
    // End of variables declaration//GEN-END:variables
}
