/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package superapp;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuário do Windows
 */
public class ItemCarrinho extends javax.swing.JPanel {

    /**
     * Creates new form ItemCarrinho
     */
    
    Item produto;
    Carrinho carrinho;
    TelaCarrinho telaCarrinho;
    
    public ItemCarrinho(Item produto, Carrinho carrinho, TelaCarrinho telaCarrinho) {
        initComponents();
        
        this.produto = produto;
        this.carrinho = carrinho;
        this.telaCarrinho = telaCarrinho;
        
        int quantItens = carrinho.meuCarrinho.get(produto);
        
        labelNomeCarrinho.setText(produto.getNome());
        labelQtdCarrinho.setText("Quantidade: "+quantItens+" "+produto.getUnidade());
        labelPrecoUn.setText("Valor un.: R$"+String.format("%.2f", produto.getPreco()));
        labelPrecoTotal.setText("Total: R$"+String.format("%.2f", produto.getPreco()*quantItens));
        
        try{
            java.io.File arquivoImagem = new java.io.File("src/main/java" + produto.getImg());
    
            if(arquivoImagem.exists()) {
                ImageIcon iconeOriginal = new ImageIcon(arquivoImagem.getAbsolutePath());

                java.awt.Image imgRedimensionada = iconeOriginal.getImage().getScaledInstance(
                    labelImgCarrinho.getPreferredSize().width, 
                    labelImgCarrinho.getPreferredSize().height, 
                    java.awt.Image.SCALE_SMOOTH
                );
        
            labelImgCarrinho.setIcon(new ImageIcon(imgRedimensionada));
            labelImgCarrinho.setText(""); 
            }
            else {
                labelImgCarrinho.setText("Sem foto");
            }
        }
        catch(Exception e){
            labelImgCarrinho.setText("Erro!");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        labelImgCarrinho = new javax.swing.JLabel();
        labelNomeCarrinho = new javax.swing.JLabel();
        labelQtdCarrinho = new javax.swing.JLabel();
        labelPrecoUn = new javax.swing.JLabel();
        labelPrecoTotal = new javax.swing.JLabel();
        spinnerQtdRemover = new javax.swing.JSpinner();
        btnRemover = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(510, 102));
        setLayout(null);

        labelImgCarrinho.setForeground(new java.awt.Color(0, 0, 0));
        labelImgCarrinho.setText("img");
        labelImgCarrinho.setPreferredSize(new java.awt.Dimension(60, 60));
        add(labelImgCarrinho);
        labelImgCarrinho.setBounds(12, 17, 64, 60);

        labelNomeCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNomeCarrinho.setForeground(new java.awt.Color(0, 0, 0));
        labelNomeCarrinho.setText("Nome");
        add(labelNomeCarrinho);
        labelNomeCarrinho.setBounds(90, 10, 280, 32);

        labelQtdCarrinho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelQtdCarrinho.setForeground(new java.awt.Color(0, 0, 0));
        labelQtdCarrinho.setText("Quantidade");
        add(labelQtdCarrinho);
        labelQtdCarrinho.setBounds(90, 70, 100, 16);

        labelPrecoUn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPrecoUn.setForeground(new java.awt.Color(0, 0, 0));
        labelPrecoUn.setText("Preço un.");
        add(labelPrecoUn);
        labelPrecoUn.setBounds(220, 70, 130, 16);

        labelPrecoTotal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelPrecoTotal.setForeground(new java.awt.Color(0, 0, 0));
        labelPrecoTotal.setText("jLabel5");
        add(labelPrecoTotal);
        labelPrecoTotal.setBounds(230, 30, 160, 22);

        spinnerQtdRemover.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        add(spinnerQtdRemover);
        spinnerQtdRemover.setBounds(430, 40, 70, 22);

        btnRemover.setBackground(new java.awt.Color(255, 0, 0));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(255, 255, 255));
        btnRemover.setText("Remover");
        btnRemover.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRemover.addActionListener(this::btnRemoverActionPerformed);
        add(btnRemover);
        btnRemover.setBounds(410, 0, 110, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        int qtdRemover = (int) spinnerQtdRemover.getValue();
        int qtdItem = carrinho.meuCarrinho.get(produto);
        
        if(qtdItem<=qtdRemover){
            carrinho.meuCarrinho.remove(produto);
            JOptionPane.showMessageDialog(null, "Produto removido do carrinho!");
            carrinho.quantTotalItens-=qtdItem;
            carrinho.valorTotalItens-=(qtdItem*produto.preco);
        }
        else{
            carrinho.meuCarrinho.put(produto, qtdItem-qtdRemover);
            JOptionPane.showMessageDialog(null, "Unidades removidas do carrinho!");
            carrinho.quantTotalItens-=qtdRemover;
            carrinho.valorTotalItens-=(qtdRemover*produto.preco);
        }
        
        telaCarrinho.inicializarCarrinho(carrinho);
    }//GEN-LAST:event_btnRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton jButton1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelImgCarrinho;
    private javax.swing.JLabel labelNomeCarrinho;
    private javax.swing.JLabel labelPrecoTotal;
    private javax.swing.JLabel labelPrecoUn;
    private javax.swing.JLabel labelQtdCarrinho;
    private javax.swing.JSpinner spinnerQtdRemover;
    // End of variables declaration//GEN-END:variables
}
