/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package superapp;

import java.util.ArrayList;
import java.util.Map;

/**
 *
 * @author Usuário do Windows
 */
public class TelaCarrinho extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCarrinho.class.getName());
    /** Creates new form TelaCarrinho */
    
    sistemabancario.Conta conta;
    sistemabancario.Transacao transacao;
    Carrinho carrinho;
    
    public TelaCarrinho(Carrinho carrinhoNovo, sistemabancario.Conta conta, sistemabancario.Transacao transacao) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.carrinho = carrinhoNovo;
        this.conta = conta;
        this.transacao = transacao;
        inicializarCarrinho(carrinhoNovo);
    }
    
    public void inicializarCarrinho(Carrinho carrinho){
        panelItensCarrinho.removeAll();

        ItemMercado it;

        for(Map.Entry<Item, Integer> map : carrinho.meuCarrinho.entrySet()){
            Item itmapa = map.getKey();
            ItemCarrinho itemVisual = new ItemCarrinho(itmapa, carrinho, this);
            panelItensCarrinho.add(itemVisual);
        }
        
        labelQtdItens.setText("Itens: "+carrinho.quantTotalItens);
        labelValorTotal.setText("Total: R$"+String.format("%.2f", carrinho.valorTotalItens));

        panelItensCarrinho.revalidate();
        panelItensCarrinho.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelQtdItens = new javax.swing.JLabel();
        labelValorTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelItensCarrinho = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carrinho");
        setMinimumSize(new java.awt.Dimension(520, 530));
        setPreferredSize(new java.awt.Dimension(535, 570));
        setSize(new java.awt.Dimension(520, 530));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carrinho");

        jButton1.setBackground(new java.awt.Color(255, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Checkout");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 520, 60);

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));

        labelQtdItens.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelQtdItens.setText("jLabel2");

        labelValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelValorTotal.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelQtdItens, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(labelValorTotal)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValorTotal)
                    .addComponent(labelQtdItens))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 460, 520, 70);

        panelItensCarrinho.setLayout(new java.awt.GridLayout(0, 1, 0, 5));
        jScrollPane2.setViewportView(panelItensCarrinho);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 60, 520, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        TelaCheckout tck = new TelaCheckout(conta, transacao, carrinho);
        tck.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelQtdItens;
    private javax.swing.JLabel labelValorTotal;
    private javax.swing.JPanel panelItensCarrinho;
    // End of variables declaration//GEN-END:variables

}
