/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package superapp;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuário do Windows
 */
public class TelaCheckout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCheckout.class.getName());

    /**
     * Creates new form TelaCheckout
     */
    
    sistemabancario.Conta conta;
    sistemabancario.Transacao transacao;
    Carrinho carrinho;
            
    public TelaCheckout(sistemabancario.Conta conta, sistemabancario.Transacao transacao, Carrinho carrinho) {
        initComponents();
        
        this.conta = conta;
        this.transacao = transacao;
        this.carrinho = carrinho;
        
        labelValorCompra.setText("R$"+String.format("%.2f", carrinho.valorTotalItens));
        labelSaldo.setText("R$"+String.format("%.2f", conta.saldo));
        
        if(carrinho.valorTotalItens-conta.saldo<0)
            labelSaldoSobra.setText("Saldo insuficiente.");
        else{
            labelSaldoSobra.setText("R$"+String.format("%.2f", carrinho.valorTotalItens));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelValorCompra = new javax.swing.JLabel();
        labelSaldoSobra = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        labelSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Checkout");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 300, 63);

        jPanel4.setBackground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 270, 300, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Valor da compra:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(52, 33, 117, 20);

        btnComprar.setBackground(new java.awt.Color(0, 102, 51));
        btnComprar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setText("Finalizar compra");
        btnComprar.addActionListener(this::btnComprarActionPerformed);
        jPanel3.add(btnComprar);
        btnComprar.setBounds(66, 160, 142, 27);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Saldo na conta:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(66, 59, 103, 20);

        labelValorCompra.setForeground(new java.awt.Color(0, 0, 0));
        labelValorCompra.setText("jLabel5");
        jPanel3.add(labelValorCompra);
        labelValorCompra.setBounds(190, 36, 37, 20);

        labelSaldoSobra.setForeground(new java.awt.Color(0, 0, 0));
        labelSaldoSobra.setText("jLabel5");
        jPanel3.add(labelSaldoSobra);
        labelSaldoSobra.setBounds(190, 90, 60, 16);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(32, 85, 220, 10);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Saldo após a compra: ");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 90, 150, 20);

        labelSaldo.setForeground(new java.awt.Color(0, 0, 0));
        labelSaldo.setText("jLabel5");
        jPanel3.add(labelSaldo);
        labelSaldo.setBounds(190, 60, 37, 20);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 60, 400, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        if(carrinho.valorTotalItens-conta.saldo>=0){
            conta.saldo-=carrinho.valorTotalItens;
            carrinho.meuCarrinho.clear();
            transacao.extrato.add(new sistemabancario.Transacao(transacao.codigo++, "Compra", carrinho.valorTotalItens, conta.senha, conta.nomeMeliante, conta.saldo));
            JOptionPane.showMessageDialog(null, "Compra concluída!");
            this.dispose();
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JLabel labelSaldoSobra;
    private javax.swing.JLabel labelValorCompra;
    // End of variables declaration//GEN-END:variables
}
