/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package superapp;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Usuário do Windows
 */
public class TelaCriarConta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCriarConta.class.getName());
    sistemabancario.Conta conta = new sistemabancario.Conta();
    
    /**
     * Creates new form TelaCriarConta
     */
    public TelaCriarConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoCriacaoNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelNum = new javax.swing.JLabel();
        labelDig = new javax.swing.JLabel();
        campoCriacaoSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criação de conta");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Criação de conta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 393, 61);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(91, 122, 40, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome do titular:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(31, 82, 100, 20);

        campoCriacaoNome.setBackground(new java.awt.Color(255, 255, 255));
        campoCriacaoNome.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoCriacaoNome);
        campoCriacaoNome.setBounds(137, 82, 144, 22);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("A senha deve ser  ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(137, 150, 100, 16);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("e conter ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 160, 110, 16);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Criar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 210, 72, 27);

        labelNum.setForeground(new java.awt.Color(0, 0, 0));
        labelNum.setText("numérica");
        jPanel1.add(labelNum);
        labelNum.setBounds(230, 150, 80, 16);

        labelDig.setForeground(new java.awt.Color(0, 0, 0));
        labelDig.setText("4 dígitos.");
        jPanel1.add(labelDig);
        labelDig.setBounds(220, 160, 60, 16);

        campoCriacaoSenha.setBackground(new java.awt.Color(255, 255, 255));
        campoCriacaoSenha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(campoCriacaoSenha);
        campoCriacaoSenha.setBounds(140, 120, 140, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nome = campoCriacaoNome.getText().toLowerCase();
        char[] charSenha = campoCriacaoSenha.getPassword();
        String senha = new String(charSenha);
        
        if(senha.length()!=4||!senha.matches("\\d+")){
            JOptionPane.showMessageDialog(null, "Senha inválida");
            
            labelDig.setForeground(Color.red);
            labelNum.setForeground(Color.red);

            int tempo = 1000;
            Timer enrole = new Timer(tempo, e -> {
                labelDig.setForeground(Color.black);
                labelNum.setForeground(Color.black);
            });
            enrole.setRepeats(false);
            enrole.start();
        }
        else if(nome.isBlank())
            JOptionPane.showMessageDialog(null, "Nome inválido!");
        else{
            conta.contas.add(new sistemabancario.Conta(senha, nome, 0));
            JOptionPane.showMessageDialog(null, "Conta criada com sucesso!");
            TelaLogin tl = new TelaLogin(conta);
            tl.setVisible(true);
            this.dispose();
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCriacaoNome;
    private javax.swing.JPasswordField campoCriacaoSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDig;
    private javax.swing.JLabel labelNum;
    // End of variables declaration//GEN-END:variables
}
